In [1]:
import shutil
import os
from datetime import datetime

from jema import (
    get_latest_holdings,
    get_jema_holdings_xlsx,
    get_symbols_and_exchanges,
    append_symbols_and_exchanges,
    get_local_prices,
    get_fx_rates,
    apply_rates,
    create_jema_json,
    read_jema_json,
)
official_nav = float(input())

you are using nologin method, data you access may be limited

In [2]:
# get_jema_holdings_xlsx()
latest_holdings = get_latest_holdings()
display(latest_holdings.head())

,Holding,Security Description,Market Value,Security No.
0,37303,ABSA GROUP LTD,396383.21,BFX05H3
1,35530,ABU DHABI ISLAMIC BANK PJSC COMMON STOCK AED 1,148751.29,6001728
2,83169,ADES HOLDING CO COMMON STOCK SAR 1,303361.46,BR56KM3
3,56152,AL RAJHI BANK COMMON STOCK SAR 10,1209606.62,B12LZH9
4,131639,ALDAR PROPERTIES PJSC COMMON STOCK AED 1,211427.64,B0LX3Y2

In [3]:
symbols_and_exchanges = get_symbols_and_exchanges()
display(symbols_and_exchanges.head())

,Issuer,Security No.,Symbol,Exchange,Currency,Conv Rate
0,ABSA GROUP LTD,BFX05H3,ABG,JSE,ZAC,1
1,ABU DHABI COMMERCIAL BANK PJSC,6545464,ADCB,ADX,AED,1
2,ABU DHABI ISLAMIC BANK PJSC,6001728,ADIB,ADX,AED,1
3,ABU DHABI NATIONAL OIL CO FOR DISTRIBUTION PJSC,BYVGM64,ADNOCDIST,ADX,AED,1
4,ADES HOLDING CO,BR56KM3,2382,TADAWUL,SAR,1

In [4]:
latest_holdings_with_symbols = append_symbols_and_exchanges(latest_holdings)
display(latest_holdings_with_symbols.head())

,Security Description,Security No.,Symbol,Exchange,Currency,Conv Rate,Holding,Market Value
0,ABSA GROUP LTD,BFX05H3,ABG,JSE,ZAC,1,37303,396383.21
1,ABU DHABI ISLAMIC BANK PJSC COMMON STOCK AED 1,6001728,ADIB,ADX,AED,1,35530,148751.29
2,ADES HOLDING CO COMMON STOCK SAR 1,BR56KM3,2382,TADAWUL,SAR,1,83169,303361.46
3,AL RAJHI BANK COMMON STOCK SAR 10,B12LZH9,1120,TADAWUL,SAR,1,56152,1209606.62
4,ALDAR PROPERTIES PJSC COMMON STOCK AED 1,B0LX3Y2,ALDAR,ADX,AED,1,131639,211427.64

In [5]:
# Get new additions - ones with no symbol
new_additions = latest_holdings_with_symbols[latest_holdings_with_symbols['Symbol'] == '']
display(new_additions)

Empty DataFrame
Columns: [Security Description, Security No., Symbol, Exchange, Currency, Conv Rate, Holding, Market Value]
Index: []

In [6]:
# loop until failures is empty
while True:
    failures = get_local_prices(latest_holdings_with_symbols)
    if not failures:
        break

# failures = get_local_prices(latest_holdings_with_symbols)

display(failures)
display(latest_holdings_with_symbols.head())

Processing: JSE:ABG
Processing: ADX:ADIB
Processing: TADAWUL:2382
Processing: TADAWUL:1120
Processing: ADX:ALDAR
Processing: TADAWUL:4200
Processing: TADAWUL:2081
Processing: OTC:APHBF
Processing: NYSE:AU
Processing: TADAWUL:4321
Processing: ATHEX:AIA
Processing: LSIN:0DP9
Processing: GETTEX:318
Processing: LSE:0Q3J
Processing: GPW:BDX
Processing: JSE:DSY
Processing: TADAWUL:1303
Processing: TADAWUL:7203
Processing: DFM:EMAARDEV
Processing: DFM:EMAAR
Processing: TADAWUL:7020
Processing: ATHEX:EUROB
Processing: JSE:FSR
Processing: RUS:SIBN
Processing: RUS:GAZP
Processing: RUS:GAZP
Processing: LSE:0QQ8
Processing: LSIN:HSBK
Processing: LSE:0J39
Processing: LSE:0S2J
Processing: FX_IDC:GBPGBP
Processing: JSE:JSE
Processing: NASDAQ:KSPI
Processing: LSIN:0O8D
Processing: LSIN:0HLK
Processing: LSIN:0Q3Y
Processing: OTC:KUMBF
Processing: RUS:LKOH
Processing: RUS:LKOH
Processing: RUS:MGNT
Processing: LSE:0NUG
Processing: RUS:MDMG
Processing: LSE:MTLN
Processing: RUS:GMKN
Processing: LSIN:0RUK
Processing: LSIN:0RGC
Processing: LSIN:0MQT
Processing: OTC:MTNOF
Processing: LSIN:KAP
Processing: JSE:NPN
Processing: LSIN:0RCR
Processing: JSE:NED
Processing: JSE:NPH
Processing: LSE:55VX
Processing: RUS:NVTK
Processing: RUS:NVTK
Processing: RUS:NLMK
Processing: BVB:SNP
Processing: ATHEX:OPTIMA
Processing: GPW:PKN
Processing: BET:OTP
Processing: ATHEX:TPEIR
Processing: RUS:PLZL
Processing: GPW:PZU
Processing: TADAWUL:1010
Processing: TADAWUL:4142
Processing: RUS:ROSN
Processing: RUS:ROSN
Processing: RUS:RTKM
Processing: JSE:SLM
Processing: ATHEX:SAR
Processing: JSE:SOL
Processing: TADAWUL:1060
Processing: TADAWUL:4031
Processing: TADAWUL:7010
Processing: RUS:SBER
Processing: RUS:SBER
Processing: RUS:CHMF
Processing: JSE:SHP
Processing: JSE:SSW
Processing: RUS:AFKS
Processing: JSE:SBK
Processing: RUS:TATN
Processing: RUS:TATNP
Processing: RUS:TCSG
Processing: TADAWUL:1180
Processing: JSE:TBS
Processing: BIST:TUPRS
Processing: BIST:RAYSG
Processing: TADAWUL:4003
Processing: JSE:VAL
Processing: RUS:VTBR
Processing: JSE:WBC
Processing: RUS:X5

[]

,Security Description,Security No.,Symbol,Exchange,Currency,Conv Rate,Holding,Market Value,SP LC
0,ABSA GROUP LTD,BFX05H3,ABG,JSE,ZAC,1,37303,396383.21,23589.0
1,ABU DHABI ISLAMIC BANK PJSC COMMON STOCK AED 1,6001728,ADIB,ADX,AED,1,35530,148751.29,19.8
2,ADES HOLDING CO COMMON STOCK SAR 1,BR56KM3,2382,TADAWUL,SAR,1,83169,303361.46,19.68
3,AL RAJHI BANK COMMON STOCK SAR 10,B12LZH9,1120,TADAWUL,SAR,1,56152,1209606.62,66.6
4,ALDAR PROPERTIES PJSC COMMON STOCK AED 1,B0LX3Y2,ALDAR,ADX,AED,1,131639,211427.64,7.73

In [7]:
fx_rates = get_fx_rates(latest_holdings_with_symbols)
display(fx_rates)

{'ZAC': 0.0004513,
 'AED': 0.20246,
 'SAR': 0.1965,
 'USD': 0.74502,
 'EUR': 0.86396,
 'RON': 0.16437,
 'PLN': 0.20314,
 'RUB': 0.010426,
 'CHF': 0.9465,
 'GBP': 1.0,
 'HUF': 0.002399,
 'CZK': 0.03552,
 'TRY': 0.01589}

In [8]:
apply_rates(latest_holdings_with_symbols, fx_rates)
display(latest_holdings_with_symbols.head())
latest_holdings_with_symbols.to_csv("jema_holdings.csv", index=False)

,Security Description,Security No.,Symbol,Exchange,Currency,Conv Rate,Holding,Market Value,SP LC,SP GBP,Holding GBP
0,ABSA GROUP LTD,BFX05H3,ABG,JSE,ZAC,1,37303,396383.21,23589.0,10.645716,397117.132757
1,ABU DHABI ISLAMIC BANK PJSC COMMON STOCK AED 1,6001728,ADIB,ADX,AED,1,35530,148751.29,19.8,4.008708,142429.395240
2,ADES HOLDING CO COMMON STOCK SAR 1,BR56KM3,2382,TADAWUL,SAR,1,83169,303361.46,19.68,3.867120,321624.503280
3,AL RAJHI BANK COMMON STOCK SAR 10,B12LZH9,1120,TADAWUL,SAR,1,56152,1209606.62,66.6,13.086900,734855.608800
4,ALDAR PROPERTIES PJSC COMMON STOCK AED 1,B0LX3Y2,ALDAR,ADX,AED,1,131639,211427.64,7.73,1.565016,206017.114896

In [9]:
create_jema_json(latest_holdings_with_symbols, fx_rates, official_nav)

jd = read_jema_json()
# display(jd)
# display(jd['total_nav_gbp'])

width = max(len(k) for k in jd)
for key in sorted(jd):
    if key == 'data_timestamp':
        continue
    val = jd[key]
    print(f"    {key:<{width}} {val:>3.2f}")

    actual_pd_total          -0.63
    adjusted_nav             63.72
    equity_nav_gbp           5.69
    equity_pd_total          -0.52
    jema_price               2.72
    official_nav             67.09
    official_pd              3.05
    s_account_divs_now_gbp   66497028.00
    s_account_divs_per_share 1.64
    total_holding_gbp        230058180.00
    total_holding_non        23704414.00
    total_holding_rus        206353766.00
    total_nav_gbp            7.33

In [10]:
# copy the files to streamlit folderand git add, commit, push
script_dir = "/home/craigc/personal_workspace/FinanceDump/jema"
streamlit_dir = "/home/craigc/personal_workspace/jema-st/"

# cd into streamlit folder and git add, commit, push
os.chdir(streamlit_dir)
os.system("git fetch && git reset --hard @{u}")

shutil.copy(f"{script_dir}/jema_holdings.csv", f"{streamlit_dir}jema_holdings.csv")
shutil.copy(f"{script_dir}/jema_data.json", f"{streamlit_dir}jema_data.json")

os.system("git add jema_holdings.csv jema_data.json")

commit_message = f"Update JEMA data - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
os.system(f'git commit -m "{commit_message}"')
os.system("git push")
os.chdir(script_dir)

HEAD is now at d2e0ee6 Update JEMA data - 2026-05-21 16:12:51
[main b7a7b56] Update JEMA data - 2026-05-22 11:59:06
 2 files changed, 108 insertions(+), 108 deletions(-)
 rewrite jema_data.json (99%)

To github.com-dyler:/jema-st/jema-st
   d2e0ee6..b7a7b56  main -> main